require("Types.CSharp")

require("Types.util")
require("Types.Class")
require("Types.System")
require("Types.LuaType")
require("Types.Miscellaneous")

global StringExtensionType = require("Types.StringExtension")
global TableExtentionType = require("Types.TableExtention")

global TestVMType = require("Types.TestVM")
global TestVType = require("Types.TestV")
global TestSubVType = require("Types.TestSubV")