global typeof: function(...: any): CS.System.Type

global setcallback: function(...: any): any

global try: function(...: any): any
global clone: function(obj: any): any
global classget: function(cls: any, key: string): any
global classset: function(cls: any, key: string, value: any)

global bindevent: function(...: any): function
global istype: function(obj: any): boolean

global rrequire: function(name: string): LuaObject